### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by Rezzas** [IldarRyabkov/UnderwaterBattles#1]
<ins>Environment :</ins>
* Windows 10
* Python 3.8.8
* pygame 2.0.1

<ins>3 TypeError :</ins>
* BubbleTanks2-main\src\data\languages\__init__.py", line 8, in <module>
    def _init_texts() __-> defaultdict[list]__:

* BubbleTanks2-main\src\components\bubble_tanks_world.py", line 1119, in BubbleTanksWorld
    def save_enemies(self, enemies __: list[Enemy]__):

* BubbleTanks2-main\src\components\bubble_tanks_world.py", line 1146, in BubbleTanksWorld
    def confirm_enemies(self, enemies __: defaultdict[int]__, dx: int, dy: int):

<ins>works fine if I delete :</ins>
*  -> defaultdict[list]
*  : list[Enemy]
* : defaultdict[int]

**Comment by IldarRyabkov** [comment]
Oh, seems like this way of type hinting is supported only for python 3.9,  according to [PEP 585](https://www.python.org/dev/peps/pep-0585/). I will add Python version in requirements, thanks for your feedback!

**Comment by IldarRyabkov** [comment]
I removed those type hintings, now it should work fine.
