### ISSUE TITLE
Support AZERTY keyboards

### ISSUE THREAD

**Issue by Rezzas** [IldarRyabkov/UnderwaterBattles#2]
Can you add an option to support this kind of keyboard ?

Or maybe just add readme note like :
* in BubbleTanks2-main\src\components
* modify player.py
* look for def handle(self, e_type, e_key):
* modify 
  * pg.K_a > pg.K_q
  * pg.K_w > pg.K_z

**Comment by IldarRyabkov** [comment]
Oh, I didn't know there were other layouts. I will definitely add the ability to change controls. Thanks for the advice!

**Comment by IldarRyabkov** [comment]
Added option to change controls via settings menu.
